name: GitHub Artifacts - Release

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

permissions: write-all

env:
  CI: false
  Branches: main
  MainBranch: main
  NPMRegistry: 
  InstallCommand: 
  BuildCommand: 
  Output: 
